### ISSUE TITLE
Contact names with accented letters do not display correctly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Desktop-App#191] opened 2021-03-15 19:30 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#desktop-bugs`.

**Comment by CSab6482** [comment] 2021-03-17 22:11
Is this a duplicate of issue #130?

**Comment by zlshames** [comment] 2021-03-20 19:27
> Is this a duplicate of issue #130?

Maybe? Might be a VCF issue or maybe just bad parsing

**Closed** 2022-03-10 00:31 UTC
Labels: Bot Created
